backend:
  name: git-gateway
  branch: main
media_folder: "_site/assets/img"
public_folder: "/assets/img"
collections:
  - name: "sections"
    label: "Sections"
    folder: "/"
    create: true
    nested:
      depth: 100 # max depth to show in the collection tree
    extension: "md"
    fields:
      - { label: "Body", name: "body", widget: "markdown", required: true }
